version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    rebase-strategy: auto
    commit-message:
      prefix: deps
      prefix-development: deps-dev
      include: scope
    labels:
      - dependencies
      - npm
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
  - package-ecosystem: "npm"
    directory: "/realtime-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps
      prefix-development: deps-dev
      include: scope
    labels:
      - dependencies
      - realtime
    groups:
      realtime-server:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - docker
