services:
  app:
    ports: []
    environment:
      NEXTAUTH_URL: https://theaterprod.beegreenx.de
      NEXT_PUBLIC_REALTIME_URL: https://theaterprod.beegreenx.de/realtime
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.theater-app-prod.entrypoints: web
      traefik.http.routers.theater-app-prod.rule: Host(`theaterprod.beegreenx.de`)
      traefik.http.routers.theater-app-prod.middlewares: theater-app-prod-redirect
      traefik.http.routers.theater-app-prod.service: theater-app-prod
      traefik.http.middlewares.theater-app-prod-redirect.redirectscheme.scheme: https
      traefik.http.routers.theater-app-prod-secure.entrypoints: websecure
      traefik.http.routers.theater-app-prod-secure.rule: Host(`theaterprod.beegreenx.de`)
      traefik.http.routers.theater-app-prod-secure.tls: "true"
      traefik.http.routers.theater-app-prod-secure.tls.certresolver: myresolver
      traefik.http.routers.theater-app-prod-secure.service: theater-app-prod
      traefik.http.services.theater-app-prod.loadbalancer.server.port: 3000
      traefik.docker.network: proxy

  realtime:
    ports: []
    environment:
      CORS_ORIGIN: https://theaterprod.beegreenx.de
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.theater-realtime-prod.entrypoints: websecure
      traefik.http.routers.theater-realtime-prod.rule: Host(`theaterprod.beegreenx.de`) && PathPrefix(`/realtime`)
      traefik.http.routers.theater-realtime-prod.tls: "true"
      traefik.http.routers.theater-realtime-prod.tls.certresolver: myresolver
      traefik.http.routers.theater-realtime-prod.middlewares: theater-realtime-prod-strip
      traefik.http.routers.theater-realtime-prod.service: theater-realtime-prod
      traefik.http.middlewares.theater-realtime-prod-strip.stripprefix.prefixes: /realtime
      traefik.http.services.theater-realtime-prod.loadbalancer.server.port: 4001
      traefik.http.services.theater-realtime-prod.loadbalancer.server.scheme: http
      traefik.docker.network: proxy

networks:
  proxy:
    external: true
