services:
  auto-deploy:
    build:
      context: .
      dockerfile: deploy-service/Dockerfile
    image: ${AUTO_DEPLOY_IMAGE:-limitlessgreen/theater_autodeploy:latest}
    restart: unless-stopped
    environment:
      GIT_REMOTE_URL: ${AUTO_DEPLOY_GIT_REMOTE_URL:?set AUTO_DEPLOY_GIT_REMOTE_URL}
      GITHUB_WEBHOOK_SECRET: ${AUTO_DEPLOY_WEBHOOK_SECRET:?set AUTO_DEPLOY_WEBHOOK_SECRET}
      TARGET_BRANCH: ${AUTO_DEPLOY_TARGET_BRANCH:-main}
      DEPLOY_ENV: ${AUTO_DEPLOY_ENV:-prod}
      DEPLOY_SERVICE_NAME: ${AUTO_DEPLOY_SERVICE_NAME:-}
      COMPOSE_PROJECT_NAME: ${AUTO_DEPLOY_PROJECT_NAME:-theater}
      LISTEN_PORT: ${AUTO_DEPLOY_LISTEN_PORT:-3000}
      WEBHOOK_PATH: ${AUTO_DEPLOY_WEBHOOK_PATH:-/webhook}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - auto-deploy-repo:/opt/worktree
    ports:
      - "${AUTO_DEPLOY_WEBHOOK_PORT:-9000}:${AUTO_DEPLOY_LISTEN_PORT:-3000}"
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.auto-deploy-http.entrypoints: web
      traefik.http.routers.auto-deploy-http.rule: Host(`${AUTO_DEPLOY_HOST:?set AUTO_DEPLOY_HOST}`)
      traefik.http.routers.auto-deploy-http.middlewares: auto-deploy-https-redirect
      traefik.http.routers.auto-deploy-http.service: auto-deploy
      traefik.http.middlewares.auto-deploy-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.auto-deploy.entrypoints: ${AUTO_DEPLOY_TRAEFIK_ENTRYPOINTS:-websecure}
      traefik.http.routers.auto-deploy.rule: Host(`${AUTO_DEPLOY_HOST:?set AUTO_DEPLOY_HOST}`)
      traefik.http.routers.auto-deploy.tls: "true"
      traefik.http.routers.auto-deploy.tls.certresolver: ${AUTO_DEPLOY_TRAEFIK_CERT_RESOLVER:-myresolver}
      traefik.http.routers.auto-deploy.service: auto-deploy
      traefik.http.services.auto-deploy.loadbalancer.server.port: ${AUTO_DEPLOY_LISTEN_PORT:-3000}
      traefik.docker.network: proxy

volumes:
  auto-deploy-repo:
networks:
  proxy:
    external: true
