services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: theater-website-app:latest
    restart: unless-stopped
    depends_on:
      - db
      - realtime
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/theater?schema=public}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://example.com}
      AUTH_SECRET: ${AUTH_SECRET}
      EMAIL_SERVER: ${EMAIL_SERVER:-smtp://user:pass@smtp.example.com:587}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@example.com}
      REALTIME_SERVER_URL: http://realtime:4001
      REALTIME_AUTH_TOKEN: ${REALTIME_AUTH_TOKEN:-change-me}
      NEXT_PUBLIC_REALTIME_URL: ${NEXT_PUBLIC_REALTIME_URL:-https://example.com/realtime}
      NEXT_PUBLIC_REALTIME_PATH: ${NEXT_PUBLIC_REALTIME_PATH:-/socket.io}
      NODE_ENV: production
    ports:
      - "3000:3000"

  realtime:
    build: ./realtime-server
    image: theater-website-realtime:latest
    restart: unless-stopped
    environment:
      PORT: 4001
      SOCKET_PATH: /socket.io
      CORS_ORIGIN: ${REALTIME_CORS_ORIGIN:-https://example.com}
      REALTIME_AUTH_TOKEN: ${REALTIME_AUTH_TOKEN:-change-me}
    ports:
      - "4001:4001"

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-theater}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
