import type { OnboardingDashboardData, OnboardingSummary } from "./dashboard-schemas";

export const DEV_ONBOARDING_SUMMARY = {
  id: "dev-preview",
  title: "Onboarding Frühjahr 2024",
  periodLabel: "11. Mär – 28. Apr 2024",
  status: "active",
} as const satisfies OnboardingSummary;

export const DEV_ONBOARDING_DASHBOARD = {
  onboarding: {
    ...DEV_ONBOARDING_SUMMARY,
    statusLabel: "Aktiv",
    timeSpan: "11. März – 28. April 2024",
    participants: 12,
  },
  global: {
    kpis: [
      {
        id: "participants",
        label: "Teilnehmer gesamt",
        value: 12,
        helper: "3 neue in 7 Tagen",
        trend: { direction: "up", percentage: 25, label: "Woche" },
      },
      {
        id: "new-per-month",
        label: "Neue Teilnehmer (30T)",
        value: 6,
        trend: { direction: "up", percentage: 50, label: "Monat" },
      },
      {
        id: "median-age",
        label: "Medianalter",
        value: 24,
        helper: "Jahre",
      },
      {
        id: "focus",
        label: "Fokus acting/tech",
        value: "58% acting",
        helper: "25% tech",
      },
      {
        id: "photo",
        label: "Fotoeinverständnis",
        value: "83%",
        intent: "success",
      },
      {
        id: "gender",
        label: "Geschlechter",
        value: "58% ♀︎",
        helper: "42% ♂︎",
      },
    ],
    ageGroups: [
      { label: "18-24", value: 4, percentage: 33 },
      { label: "25-34", value: 5, percentage: 42 },
      { label: "35-44", value: 2, percentage: 17 },
      { label: "45+", value: 1, percentage: 8 },
    ],
    genderDistribution: [
      { label: "weiblich", value: 7, percentage: 58 },
      { label: "männlich", value: 5, percentage: 42 },
    ],
    focusDistribution: [
      { label: "acting", value: 7, percentage: 58, intent: "success" },
      { label: "tech", value: 3, percentage: 25, intent: "warning" },
      { label: "both", value: 2, percentage: 17, intent: "default" },
    ],
    photoConsentRate: 0.83,
    rolesActing: [
      {
        roleId: "acting_lead",
        label: "Lead",
        domain: "acting",
        normalizedShare: 0.82,
        participantShare: 42,
      },
      {
        roleId: "acting_support",
        label: "Support",
        domain: "acting",
        normalizedShare: 0.64,
        participantShare: 33,
      },
      {
        roleId: "acting_statist",
        label: "Statist",
        domain: "acting",
        normalizedShare: 0.38,
        participantShare: 50,
      },
    ],
    rolesCrew: [
      {
        roleId: "crew_stage",
        label: "Bühne",
        domain: "crew",
        normalizedShare: 0.7,
        participantShare: 40,
      },
      {
        roleId: "crew_direction",
        label: "Regieassistenz",
        domain: "crew",
        normalizedShare: 0.55,
        participantShare: 35,
      },
      {
        roleId: "crew_costume",
        label: "Kostüm",
        domain: "crew",
        normalizedShare: 0.42,
        participantShare: 30,
      },
    ],
    roleCoverage: {
      acting: 92,
      crew: 75,
    },
    roleHeatmap: [
      { x: "Lead", y: "Bühne", value: 0.68 },
      { x: "Lead", y: "Regieassistenz", value: 0.42 },
      { x: "Support", y: "Bühne", value: 0.57 },
      { x: "Support", y: "Kostüm", value: 0.36 },
      { x: "Statist", y: "Bühne", value: 0.22 },
      { x: "Statist", y: "Marketing", value: 0.18 },
    ],
    interestTopTags: [
      { label: "Impro", value: 6, percentage: 50 },
      { label: "Tanz", value: 4, percentage: 33 },
      { label: "Organisation", value: 3, percentage: 25 },
      { label: "Schnitt", value: 2, percentage: 17 },
    ],
    interestWordCloud: [
      { tag: "Impro", weight: 6 },
      { tag: "Tanz", weight: 4 },
      { tag: "Sprechtraining", weight: 3 },
      { tag: "Kamera", weight: 2 },
      { tag: "Organisation", weight: 3 },
      { tag: "Bühnenbild", weight: 2 },
      { tag: "Maske", weight: 2 },
      { tag: "Schnitt", weight: 2 },
    ],
    interestCoOccurrences: [
      { source: "Impro", target: "Tanz", weight: 4 },
      { source: "Impro", target: "Organisation", weight: 3 },
      { source: "Tanz", target: "Kamera", weight: 2 },
      { source: "Organisation", target: "Maske", weight: 2 },
      { source: "Schnitt", target: "Maske", weight: 1 },
      { source: "Bühnenbild", target: "Organisation", weight: 2 },
    ],
    interestClusters: [
      { id: "schauspiel", label: "Schauspiel", value: 9, intent: "success" },
      { id: "technik", label: "Technik", value: 5, intent: "default" },
      { id: "orga", label: "Orga", value: 4, intent: "default" },
    ],
    diversity: {
      shannon: 1.38,
      gini: 0.32,
      normalized: 0.74,
      status: "ok",
      explanation: "Shannon 1,38 · Gini 0,32",
    },
    nutrition: {
      diets: [
        { label: "Omnivor", count: 7 },
        { label: "Vegetarisch", count: 3 },
        { label: "Vegan", count: 2 },
      ],
      allergies: [
        { allergen: "Nüsse", severities: { mild: 1, mittel: 1 } },
        { allergen: "Gluten", severities: { mild: 1 } },
      ],
    },
    process: {
      steps: [
        { id: "profile", label: "Profil ausgefüllt", completionRate: 92, dropoutRate: 4 },
        { id: "preferences", label: "Präferenzen angegeben", completionRate: 85, dropoutRate: 8 },
        { id: "documents", label: "Dokumente hochgeladen", completionRate: 78, dropoutRate: 12 },
      ],
      documents: { uploaded: 10, skipped: 1, pending: 1 },
    },
  },
  allocation: {
    roles: [
      {
        roleId: "acting_lead",
        label: "Lead",
        domain: "acting",
        capacity: 2,
        demand: 4,
        candidates: [
          {
            userId: "user-1",
            name: "Alex Beispiel",
            focus: "acting",
            normalizedShare: 0.82,
            qualityFactor: 0.9,
            score: 86,
            confidence: 0.78,
            justification: "Höchster Präferenzscore",
            interests: ["Impro", "Tanz"],
            experienceYears: 5,
            adjustedScore: 88,
            fairnessPenalty: 0.1,
            delta: 0,
          },
          {
            userId: "user-2",
            name: "Chris Demo",
            focus: "both",
            normalizedShare: 0.74,
            qualityFactor: 0.82,
            score: 79,
            confidence: 0.72,
            justification: "Starke Doppelpräferenz",
            interests: ["Kamera"],
            experienceYears: 3,
            adjustedScore: 77,
            fairnessPenalty: 0.05,
            delta: -0.6,
          },
        ],
        slots: [
          {
            slotId: "acting_lead-1",
            index: 0,
            candidate: {
              userId: "user-1",
              name: "Alex Beispiel",
              focus: "acting",
              normalizedShare: 0.82,
              qualityFactor: 0.9,
              score: 86,
              confidence: 0.78,
              justification: "Top-Score",
              interests: ["Impro"],
              experienceYears: 5,
              adjustedScore: 88,
              fairnessPenalty: 0.1,
              delta: 0,
            },
            adjustedScore: 88,
            fairnessPenalty: 0.1,
            alternatives: [
              {
                userId: "user-2",
                name: "Chris Demo",
                focus: "both",
                normalizedShare: 0.74,
                qualityFactor: 0.82,
                score: 79,
                confidence: 0.72,
                justification: "Ausgleich",
                interests: ["Organisation"],
                experienceYears: 3,
                adjustedScore: 77,
                fairnessPenalty: 0.05,
                delta: -0.6,
              },
            ],
          },
          {
            slotId: "acting_lead-2",
            index: 1,
            candidate: null,
            adjustedScore: null,
            fairnessPenalty: null,
            alternatives: [
              {
                userId: "user-3",
                name: "Jamie Test",
                focus: "acting",
                normalizedShare: 0.6,
                qualityFactor: 0.7,
                score: 71,
                confidence: 0.64,
                justification: "Solide Erfahrung",
                interests: ["Sprechtraining"],
                experienceYears: 2,
                adjustedScore: 70,
                fairnessPenalty: 0.08,
                delta: -1.2,
              },
            ],
          },
        ],
        optimizedScore: 82,
        unmatchedDemand: 1,
      },
      {
        roleId: "crew_stage",
        label: "Bühnenbild",
        domain: "crew",
        capacity: 3,
        demand: 3,
        candidates: [
          {
            userId: "user-4",
            name: "Robin Muster",
            focus: "tech",
            normalizedShare: 0.68,
            qualityFactor: 0.8,
            score: 75,
            confidence: 0.7,
            justification: "Berufserfahrung",
            interests: ["Bühnenbild"],
            experienceYears: 4,
            adjustedScore: 78,
            fairnessPenalty: 0.04,
            delta: 0,
          },
        ],
        slots: [
          {
            slotId: "crew_stage-1",
            index: 0,
            candidate: {
              userId: "user-4",
              name: "Robin Muster",
              focus: "tech",
              normalizedShare: 0.68,
              qualityFactor: 0.8,
              score: 75,
              confidence: 0.7,
              justification: "Berufserfahrung",
              interests: ["Bühnenbild"],
              experienceYears: 4,
              adjustedScore: 78,
              fairnessPenalty: 0.04,
              delta: 0,
            },
            adjustedScore: 78,
            fairnessPenalty: 0.04,
            alternatives: [
              {
                userId: "user-5",
                name: "Taylor Probe",
                focus: "both",
                normalizedShare: 0.5,
                qualityFactor: 0.66,
                score: 69,
                confidence: 0.58,
                justification: "Kreatives Portfolio",
                interests: ["Maske"],
                experienceYears: 2,
                adjustedScore: 68,
                fairnessPenalty: 0.06,
                delta: -0.8,
              },
            ],
          },
          {
            slotId: "crew_stage-2",
            index: 1,
            candidate: null,
            adjustedScore: null,
            fairnessPenalty: null,
            alternatives: [],
          },
          {
            slotId: "crew_stage-3",
            index: 2,
            candidate: null,
            adjustedScore: null,
            fairnessPenalty: null,
            alternatives: [],
          },
        ],
        optimizedScore: 74,
        unmatchedDemand: 0,
      },
    ],
    fairness: [
      {
        id: "gender-balance",
        label: "Geschlechterbalance",
        value: 48,
        target: 50,
        status: "ok",
        description: "Verteilung zwischen männlich/weiblich",
      },
      {
        id: "focus-mix",
        label: "Fokus-Mix",
        value: 32,
        target: 35,
        status: "warning",
        description: "Anteil Doppel-Fokus acting+tech",
      },
      {
        id: "newcomer",
        label: "Newcomer-Anteil",
        value: 41,
        target: 40,
        status: "ok",
        description: "Personen mit <2 Jahren Erfahrung",
      },
    ],
    conflicts: [
      {
        roleId: "acting_lead",
        label: "Lead",
        slotIndex: 0,
        delta: 0.4,
        candidates: [
          { userId: "user-1", name: "Alex Beispiel", score: 88, tieBreaker: "Bühnenstunden" },
          { userId: "user-2", name: "Chris Demo", score: 87.6, tieBreaker: "Motivation" },
        ],
      },
    ],
    optimizer: {
      totalSlots: 5,
      totalAssignments: 2,
      averageScore: 82.5,
      fairnessBuckets: [
        { bucketId: "acting", label: "Acting", capacity: 3, used: 2, utilization: 0.67 },
        { bucketId: "crew", label: "Crew", capacity: 2, used: 1, utilization: 0.5 },
      ],
    },
  },
  ranking: {
    roles: [
      {
        roleId: "acting_lead",
        label: "Lead",
        domain: "acting",
        demand: 2,
        candidates: [
          {
            userId: "user-1",
            name: "Alex Beispiel",
            email: "alex@example.com",
            focus: "acting",
            rank: 1,
            normalizedShare: 0.82,
            score: 86,
            confidence: 0.78,
            experienceYears: 5,
            interests: ["Impro", "Tanz"],
            background: "Studium Schauspiel",
            notes: "Leitet Impro-Workshops.",
            otherPreferences: [
              { roleId: "acting_support", label: "Support", domain: "acting", normalizedShare: 0.6, rank: 2 },
              { roleId: "crew_stage", label: "Bühne", domain: "crew", normalizedShare: 0.4, rank: 3 },
            ],
          },
          {
            userId: "user-2",
            name: "Chris Demo",
            email: "chris@example.com",
            focus: "both",
            rank: 2,
            normalizedShare: 0.74,
            score: 79,
            confidence: 0.72,
            experienceYears: 3,
            interests: ["Organisation", "Kamera"],
            background: "Regieassistenz im Jugendtheater",
            notes: "Möchte mehr Bühnenerfahrung.",
            otherPreferences: [
              { roleId: "acting_support", label: "Support", domain: "acting", normalizedShare: 0.55, rank: 1 },
              { roleId: "crew_direction", label: "Regieassistenz", domain: "crew", normalizedShare: 0.62, rank: 2 },
            ],
          },
          {
            userId: "user-3",
            name: "Jamie Test",
            email: null,
            focus: "acting",
            rank: 3,
            normalizedShare: 0.6,
            score: 71,
            confidence: 0.64,
            experienceYears: 2,
            interests: ["Sprechtraining"],
            background: null,
            notes: "",
            otherPreferences: [
              { roleId: "acting_statist", label: "Statist", domain: "acting", normalizedShare: 0.58, rank: 1 },
            ],
          },
        ],
      },
      {
        roleId: "crew_stage",
        label: "Bühnenbild",
        domain: "crew",
        demand: 3,
        candidates: [
          {
            userId: "user-4",
            name: "Robin Muster",
            email: "robin@example.com",
            focus: "tech",
            rank: 1,
            normalizedShare: 0.68,
            score: 75,
            confidence: 0.7,
            experienceYears: 4,
            interests: ["Bühnenbild", "Maske"],
            background: "Ausbildung Veranstaltungstechnik",
            notes: null,
            otherPreferences: [
              { roleId: "crew_props", label: "Requisite", domain: "crew", normalizedShare: 0.52, rank: 2 },
            ],
          },
          {
            userId: "user-5",
            name: "Taylor Probe",
            email: "taylor@example.com",
            focus: "both",
            rank: 2,
            normalizedShare: 0.5,
            score: 69,
            confidence: 0.58,
            experienceYears: 2,
            interests: ["Maske", "Organisation"],
            background: "Freie Projekte",
            notes: "",
            otherPreferences: [
              { roleId: "crew_costume", label: "Kostüm", domain: "crew", normalizedShare: 0.6, rank: 1 },
              { roleId: "acting_support", label: "Support", domain: "acting", normalizedShare: 0.42, rank: 3 },
            ],
          },
        ],
      },
    ],
  },
  statistics: {
    participants: [
      {
        userId: "user-1",
        name: "Alex Beispiel",
        classLabel: "B1",
        age: 24,
        focus: "acting",
        actingRoleSize: "lead",
        actingRoleLabel: "Hauptrolle",
        crewRoles: ["Bühnenbild & Ausstattung"],
        interests: ["Impro", "Tanz", "Kamera"],
        dietary: ["Vegetarisch"],
        joinedAt: "2024-03-10T10:00:00.000Z",
      },
      {
        userId: "user-2",
        name: "Chris Demo",
        classLabel: "B2",
        age: 22,
        focus: "both",
        actingRoleSize: "supporting",
        actingRoleLabel: "Nebenrolle",
        crewRoles: ["Regieassistenz & Orga", "Licht & Ton"],
        interests: ["Organisation", "Schnitt"],
        dietary: ["Vegan"],
        joinedAt: "2024-03-12T10:00:00.000Z",
      },
      {
        userId: "user-3",
        name: "Jamie Test",
        classLabel: "B1",
        age: 20,
        focus: "tech",
        actingRoleSize: "ensemble",
        actingRoleLabel: "Ensemble",
        crewRoles: ["Kostüm", "Maske & Make-up"],
        interests: ["Maske", "Bühnenbild"],
        dietary: [],
        joinedAt: "2024-03-15T10:00:00.000Z",
      },
    ],
    filters: {
      classes: ["B1", "B2"],
      focuses: ["acting", "tech", "both"],
      actingRoles: ["lead", "supporting", "ensemble"],
      crewRoles: [
        "Bühnenbild & Ausstattung",
        "Regieassistenz & Orga",
        "Licht & Ton",
        "Kostüm",
        "Maske & Make-up",
      ],
    },
  },
  history: [
    {
      onboardingId: "2023-herbst",
      label: "Onboarding Herbst 2023",
      participants: 14,
      medianAge: 23,
      focusBothShare: 28,
      createdAt: "2023-09-15T10:00:00.000Z",
    },
    {
      onboardingId: "2022-fruehjahr",
      label: "Onboarding Frühjahr 2022",
      participants: 11,
      medianAge: 22,
      focusBothShare: 24,
      createdAt: "2022-03-10T10:00:00.000Z",
    },
  ],
} as const satisfies OnboardingDashboardData;
